import React from "react";
import Card from "./Card";

export default {
  title: "Card Logic",
  components: Card,
};

export const CardLogic = () => {
  return (
    <div>
      <h1>Card Logic</h1>
      <p>In this component, is where the business logic are placed.</p>
      <p>The component stored a data which got from github.</p>
      <ol>
        <li>
          First, we will loop the data and then we will add a property into the
          data with setstate. The property that will added are isprim set to
          false and id will be generated by JavaScript Library, Guid-js
        </li>
        <li>
          Second, setState will be inside the useEffect hooks to prevent
          infinite rendering{" "}
        </li>
        <li>
          Third, create a function named checkPrime and will return boolean
          value. checkPrime will takes int as an argument where will check if
          int is lower or equal to 2 then it will return false, but if int
          greater than 2, it will loop through the number divide by int starting
          from 2. if the int divide by i is equal to 0? then it will return
          false
        </li>
        <li>
          fourth, inside the useEffect, we loop through our data to get the
          number of the index + 1.
        </li>
        <li>
          fifth, inside the if else statement, if the function return true then
          we will update the data using setstate and change the value of
          property isprime to true else return null
        </li>
        <li>Lastly, we pass in our data to CardCompo component</li>
      </ol>
    </div>
  );
};
